<a href="https://colab.research.google.com/github/nithu2109/Data-Analyst-Training/blob/main/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Libraries in Python
*   Libraries are nothing but a collection of functions and tools to help us with our important and trivial tasks
*   When working with Libraries,we don't really need to know how it works,only the input annd output of the library functions are needed











In [ ]:
import numpy as np


In [ ]:
#representing a 2d matrix
matrix=[[1,2,3],
        [4,5,6],
        [5,8,9]]

#Representing a 3d matrix
 
 
 
 matrix=
 
       [ [[1,2,3],
         [4,5,6],
         [5,8,9]],
         [[1,2,3],
         [4,5,6],
         [5,8,9]],

         [[1,2,3],
         [4,5,6],
         [5,8,9]] ]

In [ ]:
matrix=[[[1,2,3],
         [4,5,6],
         [5,8,9]],
        [[1,2,3],
         [4,5,6],
         [5,8,9]],
         [[1,2,3],
         [4,5,6],
         [5,8,9]]]


In [ ]:
matrix=np.random.randn(3,3)#rows x columns

In [ ]:
matrix

array([[ 1.21133528, -0.35532682, -1.32944977],
       [ 0.39859759, -0.63618813, -2.07037187],
       [ 0.14792517, -0.79181212,  0.0913109 ]])

In [ ]:
matrix2=np.random.randn(7,3)#rows x columns
matrix2

array([[ 2.12268217, -0.65607585, -0.18919417],
       [-0.50014267,  0.013973  , -0.49795347],
       [ 0.81263343,  0.22741941,  1.43015244],
       [ 0.80219445,  0.83778694, -0.24634268],
       [ 0.3835235 ,  0.24587968, -1.12469288],
       [-1.14374225,  0.06857418,  0.85053914],
       [ 0.27584636, -0.30840118, -0.58401295]])

In [ ]:
mat1=np.random.random(10)
mat1

array([0.85450223, 0.77694922, 0.26900701, 0.70941606, 0.65438122,
       0.48357013, 0.19585379, 0.6935385 , 0.23296773, 0.39932827])

In [ ]:
mat2=np.random.randn(4,3)
mat2

array([[-0.26548265,  1.0324233 ,  0.04986925],
       [-0.76807849,  1.61316316, -0.94516092],
       [-1.0037197 ,  2.0559559 , -0.93266648],
       [ 0.41306682, -0.9533065 , -0.19259334]])

In [ ]:
from numpy.random import randn


In [ ]:
randn(4,5)

array([[-1.89455692,  0.46663777,  0.55767257, -0.36573094,  0.10477656],
       [-0.08515156, -0.64111011,  2.07308918,  2.48308128,  2.43257669],
       [ 1.38636664,  0.54483053, -0.82068937, -0.80797697, -0.8420869 ],
       [-0.48711797,  1.09911829, -1.14990798, -0.51632385, -0.82022584]])

In [ ]:
mat2


array([[-0.26548265,  1.0324233 ,  0.04986925],
       [-0.76807849,  1.61316316, -0.94516092],
       [-1.0037197 ,  2.0559559 , -0.93266648],
       [ 0.41306682, -0.9533065 , -0.19259334]])

In [ ]:
mat2.shape

(4, 3)

In [ ]:
mat2.dtype

dtype('float64')

In [ ]:
mat3=np.random.rand(8,4)

In [ ]:
mat3


array([[0.38127149, 0.32241809, 0.21127043, 0.5327361 ],
       [0.33601616, 0.81330864, 0.14829084, 0.78492975],
       [0.22612524, 0.51606763, 0.34718196, 0.4206044 ],
       [0.95650446, 0.19937993, 0.66352336, 0.94891275],
       [0.31011569, 0.11068657, 0.95966615, 0.46549023],
       [0.84533969, 0.77415652, 0.05267253, 0.55136292],
       [0.72771923, 0.38117488, 0.34535482, 0.6683767 ],
       [0.38120603, 0.86360085, 0.43770616, 0.53335143]])

In [ ]:
mat3[3][2]

0.6635233585498292

In [ ]:
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]],dtype=float)

In [ ]:
matrix.shape

(3, 3)

In [ ]:
matrix.dtype

dtype('int64')

In [ ]:
matrix

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
type(matrix)

numpy.ndarray

In [ ]:
#practise
mylist=[[1,2,3],[4,3,2],[2,8,9]]
matrix=np.array(mylist)
print(matrix)
print(type(matrix))
print(matrix.dtype)
print("Shape Of Matrix :",matrix.shape)

[[1 2 3]
 [4 3 2]
 [2 8 9]]
<class 'numpy.ndarray'>
int64
Shape Of Matrix : (3, 3)


##Special Type Of Matrices
**Unit Matrix**

In [ ]:
np.ones((3,3))#default data type is float

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

**Zero Matrix**

In [ ]:
np.zeros((3,5))##default data type is float

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((3,5),dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

**Identity Matrix**

In [ ]:
np.eye(4)##default data type is float

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

**Diag Function**

In [ ]:
#keeping a list as principle diagonal in matrix 
x=[1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
#keeping a list one level below principle diagonal in matrix 
np.diag((x),k=-1)


array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [ ]:
#keeping a list three levels principle diagonal in matrix 
np.diag((x),k=3)

array([[0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

**arange(start,stop,step)**

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#way 1
np.arange(2,40,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [ ]:
#way 2
np.array([x for x in range(10,40,2)])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

**linspace(start,stop,num)**<br>
num denotes how many numbers required

In [ ]:
np.linspace(10,40,7)

array([10., 15., 20., 25., 30., 35., 40.])

In [ ]:
np.linspace(10,40,15,endpoint=False)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38.])

In [ ]:
np.linspace(10,40,15,endpoint=False,dtype=int)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [ ]:
#problem
myarray=np.arange(22,42,2)
np.diag(myarray,k=-2)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 26,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 28,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 30,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 32,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 34,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 36,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 38,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 40,  0,  0]])

In [ ]:
x=len(np.arange(22,1001,2,dtype=int))

In [ ]:
x

490

In [ ]:
x=np.linspace(22,40,num=10,dtype=int)
print(x)# here x ix a vector here (1 x 10)
print(x.shape)
print(type(x))

[22 24 26 28 30 32 34 36 38 40]
(10,)
<class 'numpy.ndarray'>


In [ ]:
np.array([[1,2,3,4,5]]).shape

(1, 5)

In [ ]:
x.reshape(2,5)

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [ ]:
x.reshape(5,2)

array([[22, 24],
       [26, 28],
       [30, 32],
       [34, 36],
       [38, 40]])

In [ ]:
x=np.linspace(1,1,9,dtype=int)
x.reshape(3,3)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.random.randn(3,3)

array([[ 0.64721687,  0.38496854,  1.01500931],
       [-1.50436083, -1.19219843,  1.44256754],
       [ 1.80461543, -0.09783691, -0.26584287]])

In [ ]:
np.random.random((2,5))

array([[0.09877544, 0.23949304, 0.69842882, 0.13522456, 0.13187835],
       [0.96897568, 0.41072155, 0.47645993, 0.31314725, 0.01646174]])

**randint(start,stop,size)**

In [ ]:
np.random.randint(1,10,23)

array([5, 6, 9, 7, 4, 9, 3, 9, 6, 2, 1, 5, 3, 3, 7, 2, 7, 8, 1, 1, 7, 5,
       6])

In [ ]:
np.random.randint(1,1000,(5,5))

array([[ 25, 252, 178, 440,   7],
       [577,  12, 904, 772, 618],
       [670, 475, 867, 717, 437],
       [138,  91, 883, 338, 704],
       [763, 357, 192, 893, 197]])

**normal(start,stop,size)**

In [ ]:
# a normal distribution is one where the mean is 0
np.random.normal(1,10,(4,4))

array([[ 11.63011348,  16.37409106,   3.38839385,  -9.22695368],
       [  4.72335972,  -5.42064787,   8.39522665,  17.51491753],
       [  2.42431312,  -2.16628134,   3.89620419,  -3.95716098],
       [  0.05586544,  -0.11343623,  12.26155553, -10.20366292]])

**Day 10 Problems**

In [ ]:
#Problem 1
y=np.linspace(1,50,48)

In [ ]:
print(type(y))

<class 'numpy.ndarray'>


In [ ]:
y

array([ 1.        ,  2.04255319,  3.08510638,  4.12765957,  5.17021277,
        6.21276596,  7.25531915,  8.29787234,  9.34042553, 10.38297872,
       11.42553191, 12.46808511, 13.5106383 , 14.55319149, 15.59574468,
       16.63829787, 17.68085106, 18.72340426, 19.76595745, 20.80851064,
       21.85106383, 22.89361702, 23.93617021, 24.9787234 , 26.0212766 ,
       27.06382979, 28.10638298, 29.14893617, 30.19148936, 31.23404255,
       32.27659574, 33.31914894, 34.36170213, 35.40425532, 36.44680851,
       37.4893617 , 38.53191489, 39.57446809, 40.61702128, 41.65957447,
       42.70212766, 43.74468085, 44.78723404, 45.82978723, 46.87234043,
       47.91489362, 48.95744681, 50.        ])

In [ ]:
y.reshape(6,8)

array([[ 1.        ,  2.04255319,  3.08510638,  4.12765957,  5.17021277,
         6.21276596,  7.25531915,  8.29787234],
       [ 9.34042553, 10.38297872, 11.42553191, 12.46808511, 13.5106383 ,
        14.55319149, 15.59574468, 16.63829787],
       [17.68085106, 18.72340426, 19.76595745, 20.80851064, 21.85106383,
        22.89361702, 23.93617021, 24.9787234 ],
       [26.0212766 , 27.06382979, 28.10638298, 29.14893617, 30.19148936,
        31.23404255, 32.27659574, 33.31914894],
       [34.36170213, 35.40425532, 36.44680851, 37.4893617 , 38.53191489,
        39.57446809, 40.61702128, 41.65957447],
       [42.70212766, 43.74468085, 44.78723404, 45.82978723, 46.87234043,
        47.91489362, 48.95744681, 50.        ]])

In [ ]:
y.reshape(12,4)

array([[ 1.        ,  2.04255319,  3.08510638,  4.12765957],
       [ 5.17021277,  6.21276596,  7.25531915,  8.29787234],
       [ 9.34042553, 10.38297872, 11.42553191, 12.46808511],
       [13.5106383 , 14.55319149, 15.59574468, 16.63829787],
       [17.68085106, 18.72340426, 19.76595745, 20.80851064],
       [21.85106383, 22.89361702, 23.93617021, 24.9787234 ],
       [26.0212766 , 27.06382979, 28.10638298, 29.14893617],
       [30.19148936, 31.23404255, 32.27659574, 33.31914894],
       [34.36170213, 35.40425532, 36.44680851, 37.4893617 ],
       [38.53191489, 39.57446809, 40.61702128, 41.65957447],
       [42.70212766, 43.74468085, 44.78723404, 45.82978723],
       [46.87234043, 47.91489362, 48.95744681, 50.        ]])

In [ ]:
y.reshape(4,12)

array([[ 1.        ,  2.04255319,  3.08510638,  4.12765957,  5.17021277,
         6.21276596,  7.25531915,  8.29787234,  9.34042553, 10.38297872,
        11.42553191, 12.46808511],
       [13.5106383 , 14.55319149, 15.59574468, 16.63829787, 17.68085106,
        18.72340426, 19.76595745, 20.80851064, 21.85106383, 22.89361702,
        23.93617021, 24.9787234 ],
       [26.0212766 , 27.06382979, 28.10638298, 29.14893617, 30.19148936,
        31.23404255, 32.27659574, 33.31914894, 34.36170213, 35.40425532,
        36.44680851, 37.4893617 ],
       [38.53191489, 39.57446809, 40.61702128, 41.65957447, 42.70212766,
        43.74468085, 44.78723404, 45.82978723, 46.87234043, 47.91489362,
        48.95744681, 50.        ]])

In [ ]:
y.reshape(1,48)

array([[ 1.        ,  2.04255319,  3.08510638,  4.12765957,  5.17021277,
         6.21276596,  7.25531915,  8.29787234,  9.34042553, 10.38297872,
        11.42553191, 12.46808511, 13.5106383 , 14.55319149, 15.59574468,
        16.63829787, 17.68085106, 18.72340426, 19.76595745, 20.80851064,
        21.85106383, 22.89361702, 23.93617021, 24.9787234 , 26.0212766 ,
        27.06382979, 28.10638298, 29.14893617, 30.19148936, 31.23404255,
        32.27659574, 33.31914894, 34.36170213, 35.40425532, 36.44680851,
        37.4893617 , 38.53191489, 39.57446809, 40.61702128, 41.65957447,
        42.70212766, 43.74468085, 44.78723404, 45.82978723, 46.87234043,
        47.91489362, 48.95744681, 50.        ]])

In [ ]:
y.reshape(48,1)

array([[ 1.        ],
       [ 2.04255319],
       [ 3.08510638],
       [ 4.12765957],
       [ 5.17021277],
       [ 6.21276596],
       [ 7.25531915],
       [ 8.29787234],
       [ 9.34042553],
       [10.38297872],
       [11.42553191],
       [12.46808511],
       [13.5106383 ],
       [14.55319149],
       [15.59574468],
       [16.63829787],
       [17.68085106],
       [18.72340426],
       [19.76595745],
       [20.80851064],
       [21.85106383],
       [22.89361702],
       [23.93617021],
       [24.9787234 ],
       [26.0212766 ],
       [27.06382979],
       [28.10638298],
       [29.14893617],
       [30.19148936],
       [31.23404255],
       [32.27659574],
       [33.31914894],
       [34.36170213],
       [35.40425532],
       [36.44680851],
       [37.4893617 ],
       [38.53191489],
       [39.57446809],
       [40.61702128],
       [41.65957447],
       [42.70212766],
       [43.74468085],
       [44.78723404],
       [45.82978723],
       [46.87234043],
       [47

**Vstack**

In [ ]:
#Problem 2
mat1=[[1,2,3],
      [4,5,6]]

In [ ]:
x=np.array(mat1)

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y=np.array([[7,8,9],[10,11,12]])

In [ ]:
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
z=np.vstack((x,y))

In [ ]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**Hstack**

In [ ]:
n1=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [ ]:
n2=np.array([[44],
             [55],
             [66]])

In [ ]:
n3=np.hstack((n1,n2))

In [ ]:
n3

array([[ 1,  2,  3, 44],
       [ 4,  5,  6, 55],
       [ 7,  8,  9, 66]])

***Practise Questions***

In [ ]:
x=np.random.randint(1,50,(5,5))

In [ ]:
x

array([[15,  7, 33, 19, 47],
       [47, 25, 37,  5, 49],
       [16, 48, 36,  9, 22],
       [25, 25, 13, 10, 20],
       [37,  4, 49, 48, 44]])

In [ ]:
x[1:3,1:4]

array([[25, 37,  5],
       [48, 36,  9]])

In [ ]:
y=np.random.randint(1,60,(5,5))

In [ ]:
y

array([[15, 39, 21, 27, 45],
       [12, 43, 30,  1, 50],
       [42, 26, 43, 40, 18],
       [18, 31, 27, 44, 27],
       [32, 10, 51, 34, 17]])

In [ ]:
y[1:4,2:5]=np.zeros((3,3),dtype=int)

In [ ]:
y

array([[15, 39, 21, 27, 45],
       [12, 43,  0,  0,  0],
       [42, 26,  0,  0,  0],
       [18, 31,  0,  0,  0],
       [32, 10, 51, 34, 17]])

**Append()**

In [ ]:
z=np.random.randint(1,100,(5,5))

In [ ]:
z

array([[41, 55, 45, 44,  8],
       [ 9, 22, 15, 73, 45],
       [44, 24,  9, 32, 72],
       [37, 54,  5,  4, 49],
       [33, 99, 98, 43, 38]])

In [ ]:
np.append(z,[[9,46,73,50,39]])

array([41, 55, 45, 44,  8,  9, 22, 15, 73, 45, 44, 24,  9, 32, 72, 37, 54,
        5,  4, 49, 33, 99, 98, 43, 38,  9, 46, 73, 50, 39])

*horizontal append*

In [ ]:
np.append(z,[[9,46,73,50,39]],axis=0)

array([[41, 55, 45, 44,  8],
       [ 9, 22, 15, 73, 45],
       [44, 24,  9, 32, 72],
       [37, 54,  5,  4, 49],
       [33, 99, 98, 43, 38],
       [ 9, 46, 73, 50, 39]])

*vertical append*

In [ ]:
np.append(z,[[9],
             [46],
             [73],
             [50],
             [40]],axis=1)

array([[41, 55, 45, 44,  8,  9],
       [ 9, 22, 15, 73, 45, 46],
       [44, 24,  9, 32, 72, 73],
       [37, 54,  5,  4, 49, 50],
       [33, 99, 98, 43, 38, 40]])

In [ ]:
b=np.random.randint(2,80,(4,4))

In [ ]:
b

array([[ 5, 42, 34, 54],
       [44, 72, 29, 42],
       [ 8, 69, 18, 22],
       [17, 21, 37, 47]])

In [ ]:
mat=np.insert(b,2,0,axis=0)

In [ ]:
mat

array([[ 5, 42, 34, 54],
       [44, 72, 29, 42],
       [ 0,  0,  0,  0],
       [ 8, 69, 18, 22],
       [17, 21, 37, 47]])

In [ ]:
np.unique(mat,axis=0)
#without mentioning axis it shows all unique values in the form of vector

array([[ 0,  0,  0,  0],
       [ 5, 42, 34, 54],
       [ 8, 69, 18, 22],
       [17, 21, 37, 47],
       [44, 72, 29, 42]])

***BroadCasting***

In [ ]:
mat1=np.array([[1,2,3],
               [4,5,6]])

In [ ]:
mat2=np.array([[3,4,5],
               [0,2,1]])

In [ ]:
np.add(mat1,[1,2,3])
#here one row is used 2 times

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
np.add(mat1,[[1],
             [1]])

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
mat1+mat2

array([[4, 6, 8],
       [4, 7, 7]])

***Assignment***